### ISSUE TITLE
Unable to format on save worlds.verse

### ISSUE THREAD

**Issue by rootVIII** [Manifest-Git/verse-extension#2]
Hi there. I was hoping to try this plugin in VSCode to format on save. I have installed it. But it doesn't seem to be recognized.

I am putting in my settings.json as I normally would with other languages:
```
{
    "[javascript]": {
        "editor.formatOnSave": true,
        "editor.defaultFormatter": "dbaeumer.vscode-eslint",
        "editor.codeActionsOnSave": {
            "source.fixAll.eslint": true
        }
    },
    "[verse]": {
        "editor.formatOnSave": true,
        "editor.defaultFormatter": "worlds.verse"
    },
    "[python]": {
        "editor.formatOnSave": true,
        "editor.defaultFormatter": "ms-python.autopep8"
    },
    "[go]": {
        "editor.formatOnSave": true,
        "editor.defaultFormatter": "golang.go"
    },
    "[json]": {
        "editor.quickSuggestions": {
            "strings": true
        },
        "editor.suggest.insertMode": "replace"
    },
    "[cpp]": {
        "editor.defaultFormatter": "ms-vscode.cpptools"
    },
    "C_Cpp.clang_format_fallbackStyle": "{ BasedOnStyle: Google, IndentWidth: 4, ColumnLimit: 0}"
}
```

I used worlds.verse because that is the <b>Identifier</b> shown on your page:

![sc](https://github.com/Manifest-Git/verse-extension/assets/30498791/67062adb-1026-4ae0-a324-9f168db8c5bd)

The error that I see is as shown:
```
[{
	"resource": "/C:/Users/omitted/AppData/Roaming/Code/User/settings.json",
	"owner": "_generated_diagnostic_collection_name_#2",
	"code": "1",
	"severity": 4,
	"message": "Value is not accepted. Valid values: null, \"ms-python.autopep8\", \"ms-vscode.cpptools\", \"vscode.css-language-features\", \"ms-python.flake8\", \"golang.go\", \"vscode.html-language-features\", \"vscode.json-language-features\", \"vscode.markdown-language-features\", \"vscode.php-language-features\", \"ms-vscode.powershell\", \"ms-python.pylint\", \"ms-python.python\", \"vscode.references-view\", \"vscode.search-result\", \"hashicorp.terraform\", \"vscode.typescript-language-features\", \"epicgames.verse\", \"dbaeumer.vscode-eslint\", \"ms-python.vscode-pylance\", \"vscode.configuration-editing\", \"vscode.debug-auto-launch\", \"vscode.debug-server-ready\", \"vscode.emmet\", \"vscode.extension-editing\", \"vscode.git\", \"vscode.git-base\", \"vscode.github\", \"vscode.github-authentication\", \"vscode.grunt\", \"vscode.gulp\", \"vscode.ipynb\", \"vscode.jake\", \"ms-vscode.js-debug\", \"ms-vscode.js-debug-companion\", \"vscode.markdown-math\", \"vscode.media-preview\", \"vscode.merge-conflict\", \"vscode.microsoft-authentication\", \"vscode.npm\", \"ms-vscode-remote.remote-wsl\", \"ms-vscode-remote.remote-wsl-recommender\", \"vscode.simple-browser\", \"vscode.tunnel-forwarding\", \"ms-vscode.vscode-js-profile-table\".",
	"startLineNumber": 11,
	"startColumn": 36,
	"endLineNumber": 11,
	"endColumn": 43
}]
```

Any suggestions? Thank you!

**Comment by aliensouls** [comment]
works for me out of the box, VScode version 1.87.2 .  maybe it was fixed in recent versions. just started using it, colors work 😀

**Comment by jjohnson5253** [comment]
@rootVIII This extension only provides syntax highlighting for Verse files, not code formatting capabilities.

The error occurs because VS Code can't find a formatter when you set "editor.defaultFormatter": "worlds.verse".

To fix this, remove the Verse formatting configuration from your settings.json.

You'll still get syntax highlighting without the formatting errors.
